// <auto-generated />
using MarketMechanicsDemo.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketMechanicsDemo.Server.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20200711194555_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("MarketMechanicsDemo.Shared.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyOrSell")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FillPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("LimitOrMarket")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumSharesInital")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumSharesRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimePlaced")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
